# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --ignore-scripts

# Copy source files
COPY . .

# Build the project
RUN pnpm run build

# Expose the port if needed (MCP server might use stdio protocols, so this may not be required)

# Command to run the MCP server
CMD ["node", "build/index.js"]
